name: Pull Request

on:
  pull_request:



jobs:
  test:
    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x
    uses: ./.github/workflows/x-test.yml
    with:
      node-version: ${{matrix.node-version}}
